### ISSUE TITLE
How to enable OOP Algorthm in xDrip?

### ISSUE THREAD

**Issue by jroth-haj** [tzachi-dar/LibreOOPAlgorithm#16]
Succesfully installed APK.
In xDrip, how can I check if its working?
Can't activate the Checkbox OOP Kalibration Algorithm in xDrip.

**Comment by LTorrao** [comment]
In my case:

Settings -> less common settings -> other misc options -> Out of Process Libre Algorithm (CHECK)

**Comment by jroth-haj** [comment]
I can't check this checkbox. It's disabled and unchecked.

**Comment by sandb** [comment]
I'm my case, I can also run the OOPalgorithm app, which displays the text "Algorithm worked correctly". Furthermore, I've configured in settings -> Apps & Notifications -> Recently opened apps -> OOPalgorithm -> Advanced -> Battery -> Battery optimization = Not optimized. Hope it helps.

**Comment by jroth-haj** [comment]
I'll check the Battery settings.
The App tells me "Algorithm worked correctly"
Also will try an other xDrip Version.
Currently I've the last nightly.

**Comment by jroth-haj** [comment]
The same issue with other xDrip versions.
Must I also install the libre app from Abbott???

**Comment by LTorrao** [comment]
I'm on nightly from 4 march. Are you sure about this? In Settings -> less common settings -> other misc options...

You have 2 checkboxes, one that says:

"Out of Process Libre Algorithm" (CHECK)

And the one that I also have grayed out is "OOP algorithm calibration", but that is not the one I had to activate, rather the previous.

I haven't installed Abbott's

**Comment by jroth-haj** [comment]
That's it!
In the German translation it's "external libre algorithm"
Thanks a lot!!!

**Comment by jroth-haj** [comment]
That's it!
In the German translation it's "external libre algorithm"
Thanks a lot!!!

**Comment by LTorrao** [comment]
Great news. I've been using it for about 2 weeks and it gives exactly the same in xDrip as in the reader. It's amazing work. I hope this will be available with future versions of libre as well (it seems there will be an update in libre 1 and then later libre 2 will come too (already available in Germany, I think)

**Comment by jroth-haj** [comment]
I was able to activate it.
There is a other open issue when using Miaomiao.  :-(
So I only tested it by NFC scanning.

**Comment by LTorrao** [comment]
You mean, libre 2?

**Comment by jroth-haj** [comment]
No. I still have libre1. While I activated the Oop option, the Miaomiao wasn't working.

**Comment by LTorrao** [comment]
Ok. I do it like this:

1) Install MM (charged) on the sensor
2) Install xDrip and OOPAlgorithm
4) Open xDrip
3) Open OOPAlgorithm ( it should say it worked correctly
4) Now its time to connect, add the Bluetooth device (MM) in xDrip and wait for 5/10 minutes to start reading
5) You should get the exact same values both in xDrip and in the Abbot reader, considering that they can be up to 5 minutes apart

Note: If you had already added it previously and it fails to connect try "forget device" and then re-add it. ( And wait 5 to 10 minutes to start reading)

Please let me know if it worked for you or, otherwise, if you need my help. Regards

**Comment by LTorrao** [comment]
PS. I usually activate it with the Abbot reader, not xDrip. Then have to wait 1 hour to start working

**Comment by LTorrao** [comment]
PPS. If you are in DE it might be worth it to go with Libre 2. I can't wait to have it in PT. And I hope it works with xDrip and MiaoMiao and the lovely OOPAlgorithm. Because this configuration is great with 1 already.

**Comment by dabear** [comment]
Libre 2 doesn't work with the oooalgorithm.

**Comment by LTorrao** [comment]
So the MiaoMiao and xDrip setup will not be possible with Libre 2?

**Comment by tzachi-dar** [comment]
@jroth-haj I'm not sure I follow. Do you have the miaomiao working with the oop?

**Comment by jroth-haj** [comment]
@tzachi-dar after I followed the instructions from @LTorrao and first forgot the MM, I get values now.
