### ISSUE TITLE
Surface the boolean "usedefaultstatealways" so it can be set 

### ISSUE THREAD

**Issue by JtxGit** [tzachi-dar/LibreOOPAlgorithm#19]
I have quite easily managed to create the final apk by using the scripts, but would like to also experiment by changing some java code.

I have imported this source into Android Studio, but have not (yet?) managed to build it successfully. If I could, I can easily do this change myself, but until then I need some support if possible.
The best would be if someone can explain the process required to build this project in Android Studio (as I understand, the "app-debug.apk" is used by the script to build the final apk, so I need to create the app-debug.apk first). 

Alternatively, it would be great if the boolean "usedefaultstatealways" can be made accessible:
`static public OOPResults RunAlgorithm(long timestamp, Context context, byte[] packet, boolean usedefaultstatealways, String sensorid)` 
so it is not a permanent false:
`OOPResults oOPResults = AlgorithmRunner.RunAlgorithm(timestamp, context, packet, false, sensorid);`

Any help would be appreciated.

**Comment by dabear** [comment]
Currently, all calls to the algorithm uses the previous calls output as input. Contact me on the gitter room and I could help you out with building your own.

**Comment by JtxGit** [comment]
Great, thanks.
I looked up "gitter" and see it is some sort of chat functionality. Now I just need to figure out how to install / use it...

**Comment by JtxGit** [comment]
Thanks, I can now build my own, so I close this one.
