### ISSUE TITLE
Error installing on Samsung S7 edge

### ISSUE THREAD

**Issue by klettervirus** [tzachi-dar/LibreOOPAlgorithm#5]
I created the *.apk and mailed it to my phone. (Size 17.347 kb). Installing gives error message: 
"App wurde nicht installiert" (App was not installed). 
Tried it twice, different ways of transferring the file. Same error, clicking the apk file results in "not installed".
Any ideas why? I would love to test the algorithm!
Thanks for the hard work, Stefan

**Comment by tzachi-dar** [comment]
Do you have android studio installed?
If yes, in what directory?

בתאריך יום ד׳, 11 ביולי 2018, 21:15, מאת klettervirus ‏<
notifications@github.com>:

**Comment by tzachi-dar** [comment]
More specifically, 
what does 
"C:\Program Files\Android\Android Studio\jre\bin\jarsigner.exe"

return?

**Comment by klettervirus** [comment]
It returns an error since I installed androidstudio in a custom directory. Will reinstall and try again!

**Comment by klettervirus** [comment]
Awesome, it is now installed. The installation path needs to be the default path!
